# Generated by Django 3.2.7 on 2022-01-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_shopuser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="age",
            field=models.PositiveIntegerField(default=0, verbose_name="возраст"),
        ),
    ]
