# Generated by Django 3.2.9 on 2022-02-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0004_auto_20220216_1254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="age",
            field=models.PositiveIntegerField(
                default=18, null=True, verbose_name="возраст"
            ),
        ),
    ]
